"""modification

Revision ID: 6fa005493b51
Revises: 8e90a8f2c556
Create Date: 2025-11-15 23:56:00.070583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa005493b51'
down_revision: Union[str, Sequence[str], None] = '8e90a8f2c556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mobile', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('portal_used', sa.String(), nullable=True))
    op.add_column('users', sa.Column('total_investment', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('terms_accepted_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'terms_accepted_date')
    op.drop_column('users', 'terms_accepted')
    op.drop_column('users', 'total_investment')
    op.drop_column('users', 'portal_used')
    op.drop_column('users', 'business_type')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'title')
    op.drop_column('users', 'company')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
